services:
  backend:
    build: .
    container_name: randomapp-backend
    ports:
      - '8000:8000'
    volumes:
      - ./app:/app/app
    env_file:
      - .env

  frontend:
    build: ./frontend
    container_name: randomapp-frontend
    ports:
      - '5173:5173'
    environment:
      - VITE_API_URL=http://localhost:8000
    depends_on:
      - backend
